hydra:
  run:
    dir: hydra_output/

comet_ml:
  api_key: YOUR_API_KEY
  project_name: YOUR_PROJECT_NAME

exp:
  exp_name: test

data:
  img_size: 128

train:
  batch_size: 64
  epoch: 5
  seed: 42
  fold: 0
  lr: 0.00005
  model_name: efficientnet-b0
